export const CREATE_FORM_REQUEST = "CREATE_FORM_REQUEST";
export const CREATE_FORM_SUCCESS = "CREATE_FORM_SUCCESS";
export const CREATE_FORM_FAIL = "CREATE_FORM_FAIL";

export const GET_FORM_QUESTIONS_REQUEST = "GET_FORM_QUESTIONS_REQUEST";
export const GET_FORM_QUESTIONS_SUCCESS = "GET_FORM_QUESTIONS_SUCCESS";
export const GET_FORM_QUESTIONS_FAIL = "GET_FORM_QUESTIONS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
